apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  labels:
    app: rootstock-safe-apps
  name: rootstock-safe-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rootstock-safe-apps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rootstock-safe-apps
    spec:
      containers:
        - image: sovryn/rootstock-safe-apps
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: rootstock-safe-apps
          name: web
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "400m"
          ports:
          - containerPort: 80
            protocol: TCP
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: rootstock-safe-apps
spec:
  selector:
    app: rootstock-safe-apps
  ports:
    - port: 443
      targetPort: 80
  type: NodePort
