version: '3'
networks:
  safe_react_apps_network:
    driver: bridge

services:
  safe:
    container_name: react-apps
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    restart: always
    networks:
      - safe_react_apps_network
